### PR TITLE
Add an example for running in Kubernetes

### PR DESCRIPTION
**Pull request by fatalbanana**
I have some doubts about it...

Is this a suitable place for such a thing and/or might we want to be providing Helm charts or so (probably it suggests we should be rolling a new bundle for each release & hosting that somewhere) ...

What technologies to focus on- do we expect that people want to use Kustomize and/or Tanka and/or Helm / something else?

What we've ended up with is ~~some variant of the pile-of-YAML approach~~ Tanka ...

There might be things which should better be here but aren't ...
We miss auxiliary services like in the docker compose example - doubtful about how to best deal with those ....

### CODE REVIEW

**Comment by dragoangel** [comment]
There is ready-to-use helm charts available https://artifacthub.io/packages/helm/ectobit/rspamd and plain kube resources isn't usable thing.

**Comment by fatalbanana** [comment]
I perceive Helm as inflexible but it might be actually sufficiently useful, I'll have to investigate. Helm users tend to try build another DSL for all configuration like in `ectobit/rspamd` & that's something I rather don't want.

An operator doesn't seem worthwhile to me (and leaves users with the similar problem about how to manage the CRDs).

**Comment by dragoangel** [comment]
> I perceive Helm as inflexible but it might be actually sufficiently useful, I'll have to investigate. Helm users tend to try build another DSL for all configuration like in `ectobit/rspamd` & that's something I rather don't want.
> 
> An operator doesn't seem worthwhile to me (and leaves users with the similar problem about how to manage the CRDs).

What exactly you see as inflexible in Helm? Can you provide examples of what you can't do with it or it creates tons of issues in? 

CRDs with Operator is a way to store and render advanced data from k8s api, usually it done to have advanced software configuration as a code without trying to render each config as a configmap that you need to mount as a volume, and that true that they have to be also rendered by Helm chart for example, but I agree it usually doesn't worthwhile hasle, I mentioned this by myself, I just describe an option.

**Comment by fatalbanana** [comment]
> What exactly you see as inflexible in Helm? Can you provide examples of what you can't do with it or it creates tons of issues in? Especially compared to plain k8s yam files or Kustomize ;)

I'm particularly interested in how we might populate configmaps from some user-supplied directories like in the example on hand or otherwise allow the user to do something similar.

**Comment by dragoangel** [comment]
> I'm particularly interested in how we might populate configmaps from some user-supplied directories like in the example on hand or otherwise allow the user to do something similar.

Go templates used in Helm allow to render any data based on values user provide to helm, it's only question of how much you want to customize, plus default values easielly merges with user supplied values that can overwrite default values. Same users can create own helm chart that will create new resources and mount them to child dependency.

**Comment by fatalbanana** [comment]
Maybe this is OK for a start. It doesn't deal with everything but that's something I'd rather avoid in favour of being extensible (I'd be happy for PRs to enable it to do all the things all the same). Idea could be to add a Helm chart in parallel loosely based on this.

**Pull request merged**
